fixes:
  - "ballerina/graphql/*/::graphql-ballerina/"  # move path of graphql
  - "ballerina/graphql$0046parser/*::graphql-ballerina/modules/parser"   # move path of graphql module - parser
  - "ballerina/graphql/0.1.3/._string_constants*::graphql-ballerina/constants.bal"

  