fixes:
  - "ballerina/graphql/0_1_3/::"  # move path   e.g., "before/path" => "after/path"
  - "ballerina/graphql$0046parser/0_1_3::/modules/parser"         # move root   e.g., "path/" => "after/path/"
