name: Code Coverage

on: [ push ]

jobs:
    code-coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
                    name: codecov-report
                    files: ./report.xml
                    directory: ./reports/jacoco/
